
#CREATE DATABASE Snootboots;

USE Snootboots;

CREATE TABLE MFGS(

	ID INT AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    ProductType VARCHAR(20),
    City VARCHAR(20),
    State VARCHAR(20),
    
    PRIMARY KEY (ID)
);

CREATE TABLE TIES(

	ID INT AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    Length INT,
    Material VARCHAR(40),
    Color VARCHAR(20),
    Mfg INT, 
    Price FLOAT(20, 2) NOT NULL,
    
    PRIMARY KEY (ID),
    FOREIGN KEY (Mfg) REFERENCES MFGS(ID)
);

CREATE TABLE BOOTS(

	ID INT AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    Shape VARCHAR(20),
    Material VARCHAR(40),
    Color VARCHAR(20),
    Mfg INT, 
    Price FLOAT(20, 2) NOT NULL,
    
    PRIMARY KEY (ID),
    FOREIGN KEY (Mfg) REFERENCES MFGS(ID)
);

CREATE TABLE CLASPS(

	ID INT AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    Type VARCHAR(20),
    Material VARCHAR(40),
    Color VARCHAR(20),
    Mfg INT, 
    Price FLOAT(20, 2) NOT NULL,
    
    PRIMARY KEY (ID),
    FOREIGN KEY (Mfg) REFERENCES MFGS(ID)
);

CREATE TABLE SNOOTBOOTS(

	ID INT AUTO_INCREMENT,
	Name VARCHAR(50) NOT NULL,
    Ties INT,
    Clasp INT,
    Boot INT,
	Price FLOAT(20, 2) NOT NULL,
    
    PRIMARY KEY (ID),
    FOREIGN KEY (Ties) REFERENCES TIES(ID),
    FOREIGN KEY (Clasp) REFERENCES CLASPS(ID),
    FOREIGN KEY (Boot) REFERENCES BOOTS(ID)
);

#Reset Everything
#DROP DATABASE Snootboots;

DROP TABLE MFGS;
DROP TABLE TIES;
DROP TABLE BOOTS;
DROP TABLE CLASPS;
DROP TABLE SNOOTBOOTS;